# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-01 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitinfo', '0002_auto_20190301_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitinfo',
            name='hprice',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='最高价格'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unitinfo',
            name='lprice',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='最低价格'),
            preserve_default=False,
        ),
    ]
