# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-01 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitinfo', '0003_auto_20190301_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitinfo',
            name='desc',
            field=models.TextField(verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='unitinfo',
            name='text',
            field=models.TextField(verbose_name='详情文字'),
        ),
    ]
