# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-27 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caipiid', models.CharField(max_length=200, verbose_name='车辆图片名称')),
                ('picture', models.ImageField(upload_to='img/car', verbose_name='图片')),
            ],
            options={
                'verbose_name': '车辆图片',
                'db_table': 'carimage',
                'verbose_name_plural': '车辆图片',
            },
        ),
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carid', models.CharField(max_length=10, verbose_name='车辆id')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('contact', models.CharField(max_length=11, verbose_name='联系方式')),
                ('desc', models.CharField(max_length=300, verbose_name='描述')),
                ('text', models.CharField(max_length=300, verbose_name='介绍文字')),
            ],
            options={
                'verbose_name': '车辆信息表',
                'db_table': 'carinfo',
                'verbose_name_plural': '车辆信息表',
            },
        ),
        migrations.AddField(
            model_name='carimage',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carinfo.CarInfo'),
        ),
    ]
